//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top2000GOED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.Lijst = new HashSet<Lijst>();
        }
    
        public int songid { get; set; }
        public int artiestid { get; set; }
        public string titel { get; set; }
        public int jaar { get; set; }
        public string verloop { get; set; }
        public byte[] foto { get; set; }
        public Nullable<int> positie { get; set; }
    
        public virtual Artiest Artiest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lijst> Lijst { get; set; }
    }
}
